POST http://127.0.0.1:8080/api/validate_chirp HTTP/1.1
content-type: application/json

{
  "body": "This is an opinion I need to share with the world"
}

###

POST http://127.0.0.1:8080/api/validate_chirp HTTP/1.1
content-type: application/json

{
  "body": "Go kerfuffle yourself"
}

###

POST http://127.0.0.1:8080/api/users HTTP/1.1
content-type: application/json

{
  "email": "user@example.com"
}

###
POST http://127.0.0.1:8080/api/chirps HTTP/1.1
content-type: application/json

{
  "body": "Hello, world!",
  "user_id": "51be2afc-5bec-4f0e-ba0b-4570aba4b9c1"
}