POST http://127.0.0.1:8080/api/validate_chirp HTTP/1.1
content-type: application/json

{
  "body": "This is an opinion I need to share with the world"
}

###

POST http://127.0.0.1:8080/api/validate_chirp HTTP/1.1
content-type: application/json

{
  "asdf": "This is junkaasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfsdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdfasdf"
}